#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App3.Resource", IsApplication=true)]

namespace App3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000e
			public const int button_ckrb = 2130968590;
			
			// aapt resource value: 0x7f04002b
			public const int button_date = 2130968619;
			
			// aapt resource value: 0x7f04000d
			public const int button_spinner = 2130968589;
			
			// aapt resource value: 0x7f04002a
			public const int button_time = 2130968618;
			
			// aapt resource value: 0x7f04000f
			public const int button_timeDate = 2130968591;
			
			// aapt resource value: 0x7f040004
			public const int cb_button = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int checkBox1 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int checkBox2 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int checkBox3 = 2130968579;
			
			// aapt resource value: 0x7f040028
			public const int datePicker1 = 2130968616;
			
			// aapt resource value: 0x7f040000
			public const int lay_cktv = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int lay_rbtv = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int lay_rgTv = 2130968584;
			
			// aapt resource value: 0x7f040029
			public const int linearLayout1 = 2130968617;
			
			// aapt resource value: 0x7f040018
			public const int linearLayout2 = 2130968600;
			
			// aapt resource value: 0x7f040021
			public const int linearLayout3 = 2130968609;
			
			// aapt resource value: 0x7f04000a
			public const int radBtn3 = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int radBtn4 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int radBtn5 = 2130968588;
			
			// aapt resource value: 0x7f040009
			public const int radG1 = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int radioButton1 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int radioButton2 = 2130968583;
			
			// aapt resource value: 0x7f040013
			public const int sp = 2130968595;
			
			// aapt resource value: 0x7f040010
			public const int tableLayout1 = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int tableRow1 = 2130968593;
			
			// aapt resource value: 0x7f040014
			public const int tableRow2 = 2130968596;
			
			// aapt resource value: 0x7f04001f
			public const int tableRow3 = 2130968607;
			
			// aapt resource value: 0x7f040027
			public const int tableRow4 = 2130968615;
			
			// aapt resource value: 0x7f040017
			public const int textView10 = 2130968599;
			
			// aapt resource value: 0x7f04001a
			public const int textView13 = 2130968602;
			
			// aapt resource value: 0x7f04001c
			public const int textView14 = 2130968604;
			
			// aapt resource value: 0x7f040023
			public const int textView15 = 2130968611;
			
			// aapt resource value: 0x7f040025
			public const int textView16 = 2130968613;
			
			// aapt resource value: 0x7f040012
			public const int textView2 = 2130968594;
			
			// aapt resource value: 0x7f040015
			public const int textView3 = 2130968597;
			
			// aapt resource value: 0x7f04001e
			public const int timePicker1 = 2130968606;
			
			// aapt resource value: 0x7f040020
			public const int tvDateLabel = 2130968608;
			
			// aapt resource value: 0x7f040026
			public const int tvDay = 2130968614;
			
			// aapt resource value: 0x7f040019
			public const int tvHour = 2130968601;
			
			// aapt resource value: 0x7f04001b
			public const int tvMin = 2130968603;
			
			// aapt resource value: 0x7f040024
			public const int tvMonth = 2130968612;
			
			// aapt resource value: 0x7f04001d
			public const int tvSec = 2130968605;
			
			// aapt resource value: 0x7f040016
			public const int tvSp = 2130968598;
			
			// aapt resource value: 0x7f040022
			public const int tvYear = 2130968610;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int ckrb = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Main = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int spinner = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int TimeDateSample = 2130837507;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int checkbox1 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int checkbox2 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int checkbox3 = 2130903043;
			
			// aapt resource value: 0x7f030005
			public const int date_seprate = 2130903045;
			
			// aapt resource value: 0x7f030004
			public const int time_seprate = 2130903044;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
